### PR TITLE
Update standard workflow files.

### PR DESCRIPTION
**Pull request by feanil**
This PR was created automatically by the `repo_checks.py` script in the
https://github.com/openedx/terraform-github repository.

### CODE REVIEW

**Review by e0d — APPROVED** [review]
:+1:

**Review by e0d — CHANGES_REQUESTED** [review]
Sorry, noticed there's an issue with CI after approving, changing my review.

```
lerna ERR! EPRESET Unable to load conventional-changelog preset 'conventionalcommits' (conventional-changelog-conventionalcommits)
Error: Process completed with exit code 1.
```

**Comment by feanil** [comment]
@adamstankiewicz @iloveagent57 I could use some guidance here, I'm trying to add the standard workflows but it looks like the CI workflow is failing.  I'm not sure how to read the failure, is it complaining about my commits or something else.

Also, it looks like your CI workflow [hasn't run on master in about 10 months](https://github.com/openedx/frontend-enterprise/actions/workflows/ci.yml?query=branch%3Amaster) is that intentional?

**Comment by adamstankiewicz** [comment]
> I could use some guidance here, I'm trying to add the standard workflows but it looks like the CI workflow is failing. I'm not sure how to read the failure, is it complaining about my commits or something else?

@feanil Our release pipeline for this repo with Lerna has been largely broken since the `openedx/cla` status check was made required. A week or two ago, @macdiesel spent some time wrangling with Lerna to try to get it to commit its changes via a PR instead of directly to `master`. We're close to a solution here, but we've been dealing with other priorities so haven't had a chance to wrap this up, unfortunately.

> Also, it looks like your CI workflow [hasn't run on master in about 10 months](https://github.com/openedx/frontend-enterprise/actions/workflows/ci.yml?query=branch%3Amaster) is that intentional?

There's no need to run the CI workflow on commits to `master`. The Release workflow is responsible for dealing with the commits to `master`. The Release workflow covers the same things as the CI workflow related to ensuring linting is done, tests are run, application is built, etc. Running CI workflow on `master` is duplicative and unnecessary.

**Comment by feanil** [comment]
@adamstankiewicz thanks for the context.  It sounds like in that case, the failure here is not related to the changes I've introduced to add standard workflows to this repo.  Do you have any objections to me merging these standard workflows with CI failing?  There was no code change to any code in this repo, just adding some github actions workflows that we're trying to standardize across all repos.

**Comment by adamstankiewicz** [comment]
@feanil Yes, this PR should be fine to merge given there's no code changes that would require a deployment to NPM.

**Pull request merged**
