### PR TITLE
build: Added support for node 16

### PR DESCRIPTION
**Pull request by Jawayria**
JIRA: https://openedx.atlassian.net/browse/BOM-3251

### CODE REVIEW

**Comment by binodpant** [comment]
Also, I think we can merge this but I am not sure, will it allow merging PRs going forward if node16 fails? or will a passing node16 node be required to merge PRs?

**Comment by Jawayria** [comment]
@binodpant @adamstankiewicz need help in updating the dependencies within the sub-packages. These packages seem to be interdependent so I'm having trouble while fixing the conflicts.

**Review by macdiesel — APPROVED** [review]

**Comment by binodpant** [comment]
Linking @adamstankiewicz 's PR which should help with this / unblock this

https://github.com/openedx/frontend-enterprise/pull/250

**Comment by johnnagro** [comment]
tackled in https://github.com/openedx/frontend-enterprise/pull/250

**Pull request closed without merging**
